name: tinhte_api

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  async: ^2.1.0
  http: any
  json_annotation: ^2.1.0
  path: ^1.6.2

dev_dependencies:
  build_runner: any
  json_serializable: any
  test: ^1.3.3
